// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_shared_int
IntegerVector get_shared_int(const char* seg_name, const char* obj_name);
RcppExport SEXP sharedata_get_shared_int(SEXP seg_nameSEXP, SEXP obj_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const char* >::type seg_name(seg_nameSEXP);
    Rcpp::traits::input_parameter< const char* >::type obj_name(obj_nameSEXP);
    __result = Rcpp::wrap(get_shared_int(seg_name, obj_name));
    return __result;
END_RCPP
}
// share_int
int share_int(const std::vector<int>& vec, const char* seg_name, const char* obj_name);
RcppExport SEXP sharedata_share_int(SEXP vecSEXP, SEXP seg_nameSEXP, SEXP obj_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const char* >::type seg_name(seg_nameSEXP);
    Rcpp::traits::input_parameter< const char* >::type obj_name(obj_nameSEXP);
    __result = Rcpp::wrap(share_int(vec, seg_name, obj_name));
    return __result;
END_RCPP
}
