# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_shared_integer_vector <- function(seg_name, obj_name) {
    .Call('sharedata_get_shared_integer_vector', PACKAGE = 'sharedata', seg_name, obj_name)
}

get_shared_numeric_vector <- function(seg_name, obj_name) {
    .Call('sharedata_get_shared_numeric_vector', PACKAGE = 'sharedata', seg_name, obj_name)
}

share_integer_vector <- function(vec, seg_name, obj_name) {
    .Call('sharedata_share_integer_vector', PACKAGE = 'sharedata', vec, seg_name, obj_name)
}

share_numeric_vector <- function(vec, seg_name, obj_name) {
    .Call('sharedata_share_numeric_vector', PACKAGE = 'sharedata', vec, seg_name, obj_name)
}

