# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_shared_raw <- function(seg_name, obj_name) {
    .Call('sharedata_get_shared_raw', PACKAGE = 'sharedata', seg_name, obj_name)
}

remove_raw <- function(seg_name) {
    .Call('sharedata_remove_raw', PACKAGE = 'sharedata', seg_name)
}

share_raw <- function(vec, seg_name, obj_name, overwrite) {
    .Call('sharedata_share_raw', PACKAGE = 'sharedata', vec, seg_name, obj_name, overwrite)
}

