# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_shared_int <- function(seg_name, obj_name) {
    .Call('sharedata_get_shared_int', PACKAGE = 'sharedata', seg_name, obj_name)
}

share_int <- function(seg_name, obj_name) {
    .Call('sharedata_share_int', PACKAGE = 'sharedata', seg_name, obj_name)
}

